allow_duplicates: true
galaxy_info:
  author: "AnsibleGuy"
  description: "Role for importing data from csv files to MySQL database"
  company: "AnsibleGuy"
  license: GNU General Public License v3.0
  min_ansible_version: 2.8
  platforms:
  galaxy_tags: [mysql, csv, ansible_forms]
  dependencies: []