---
- name: backup ansibleforms
  hosts: localhost
  become: yes
  tasks:
  - name: set backup folder name
    set_fact:
      backupfolder: "{{ data_folder }}/backups/{{ ansible_date_time.date }}-{{ ansible_date_time.time }}"
  - name: Create backup folder
    file:
      path: "{{ backupfolder }}"
      owner: root
      group: mysql
      mode: '0774'
      state: directory
  - name: Back up all databases
    mysql_db:
      state: dump
      name: AnsibleForms
      target: '{{ backupfolder }}/ansibleforms.sql'
      login_host: "{{ mysql_credential.host}}"
      login_port: "{{ mysql_credential.port}}"
      login_user: "{{ mysql_credential.user }}"
      login_password: "{{ mysql_credential.password }}"
  - name: Backup forms.yaml
    copy:
      src: "{{ data_folder }}/forms.yaml"
      dest: "{{ backupfolder }}/forms.yaml"
