# Theme settings
doks:
    baseurl:  
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: 
            image: true
        nav:
            - item_name: Introduction
              item_url: '/introduction'        
            - item_name: How to install
              item_url: '/installation'          
            - item_name: Environment Variables
              item_url: '/customization'   
            - item_name: Forms.yaml
              item_url: '/forms'        
            - item_name: GUI
              item_url: '/gui'                        
        nav2:
            - item_name: Create Forms
              item_url: '/form'        
              item_icon: table-list
            - item_name: Formfields
              item_url: '/formfield'  
              item_icon: input-text        
            - item_name: Expressions
              item_url: '/expressions'   
              item_icon: brackets-curly
            - item_name: FAQ
              item_url: '/faq' 
              item_icon: square-question               
        github_url: https://github.com/ansibleguy76
    footer:
        content:
            logo:
                text: 
                image: true
            copyright: Copyright &copy; 2023. - AnsibleForms <br>All rights reserved.
        social_list:
            #- network_name: facebook
            #  profile_url: '#'
            #- network_name: twitter
            #  profile_url: '#'
            #- network_name: instagram
            #  profile_url: '#'
            #- network_name: youtube
            #  profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/

# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]