# Theme settings
doks:
    baseurl: /ansibleforms 
    color_theme: # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: 
            image: true
        nav:
            - item_name: AnsibleForms on Github
              item_url: 'https://github.com/ansibleguy76'
    footer:
        content:
            logo:
                text: 
                image: true
            copyright: Copyright &copy; 2023. - AnsibleForms <br>All rights reserved.
        social_list:
            #- network_name: facebook
            #  profile_url: '#'
            #- network_name: twitter
            #  profile_url: '#'
            #- network_name: instagram
            #  profile_url: '#'
            #- network_name: youtube
            #  profile_url: '#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
