name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      versionCode:
        description: 'Version number (50500)'
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  createrelease:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number and name
      run: printf 'ext.version_code = ${{ github.event.inputs.versionCode }}\next.version_name = "${{ github.event.inputs.versionName }}"\n' > app_versions.gradle
    - name: Update Changelog
      run: |
        VERSION="${{ github.event.inputs.versionName }}"
        DATE=$(date +%Y-%m-%d)
        sed -i "s/## \[Unreleased\]/## [Unreleased]\n\n## [$VERSION] - $DATE/" CHANGELOG.md
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add app_versions.gradle
        git add CHANGELOG.md
        git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
        echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Create pull request into main
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        gh pr create \
          --base main \
          --head release/v${{ github.event.inputs.versionName }} \
          --title "v${{ github.event.inputs.versionName }} into main" \
          --body "This PR was created by the release workflow. Version commit: ${{ steps.make-commit.outputs.commit }}"
    - name: Create pull request to develop
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        gh pr create \
          --base develop \
          --head release/v${{ github.event.inputs.versionName }} \
          --title "v${{ github.event.inputs.versionName }} into develop" \
          --body "This PR was created by the release workflow. Version commit: ${{ steps.make-commit.outputs.commit }}"
